name: Publish to WinGet
on:
  release:
    types: [released]
jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: vedantmgoyal2009/winget-releaser@v2
        with:
          identifier: Strem.App
          max-versions-to-keep: 5
          installers-regex: '\.zip$'
          token: ${{ secrets.WINGET_TOKEN }}